[build] 
  publish = "dist"
  command = "yarn generate"

[dev] 
  publish = "dist"
  command = "ntl dev"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/fetch-routes/:splat"
  status = 200