[build] 
  publish = "dist"
  command = ""

[dev] 
  publish = "dist"
  command = ""

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/blog/*"
  to = "/.netlify/functions/fetch-routes/:splat"
  status = 200